export { default as facebook } from './facebook.svg'
export { default as github } from './github.svg'
export { default as instagram } from './instagram.svg'
export { default as site } from './site.svg'
export { default as twitter } from './twitter.svg'
export { default as vk } from './vk.svg'
export { default as youtube } from './youtube.svg'
